FROM python:3.10

WORKDIR /app

COPY /requirements.txt /app/requirements.txt
COPY ./cub/cub/celery.py /app/cub/cub/celery.py

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD sh -c "python /app/manage.py runserver 0.0.0.0:8000 & \
          python /app/manage.py bot & \
          celery -A cub worker -l info"