FROM python:3.10

WORKDIR /app

COPY /requirements.txt /app/requirements.txt
COPY ./cub/cub/celery.py /app/cub/cub/celery.py

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "manage.py", "migrate"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
