# Generated by Django 4.2.6 on 2023-11-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bik', models.CharField(max_length=4, verbose_name='БИК')),
                ('kore_bill', models.CharField(max_length=6, verbose_name='Кор счет')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название организации')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=255, null=True, verbose_name='КПП')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('header_name', models.CharField(max_length=255, verbose_name='ФИО директора')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_bank', to='customers.customerbank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['title'],
            },
        ),
    ]
