# Generated by Django 4.2.6 on 2023-11-29 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('stopped', 'завершена'), ('paused', 'остановлена'), ('new', 'новая'), ('in_work', 'в работе')], default='new', max_length=50, verbose_name='Статус задачи')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения задачи')),
                ('is_paused', models.BooleanField(default=False, verbose_name='На паузе')),
                ('is_stopped', models.BooleanField(default=False, verbose_name='Завершена')),
                ('start_timestamp', models.TimeField(blank=True, null=True, verbose_name='Время начала выполнения')),
                ('time', models.DurationField(blank=True, null=True, verbose_name='Время выполнения задачи')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Для фронта')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_files/', verbose_name='Файл к задаче')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_files', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 29, 13, 21, 50, 680083, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['date'],
            },
        ),
    ]
