# Generated by Django 4.2.6 on 2023-11-29 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 29, 13, 24, 22, 802804, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата'),
        ),
    ]
