# Generated by Django 4.2.6 on 2023-11-25 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_taskcomment_alter_task_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'programmer'), ('role', 'manager'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='executor_projects', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
