# Generated by Django 4.2.6 on 2023-11-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskcomment_options_taskcomment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задача'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_comments', to='tasks.taskcomment', verbose_name='Комментарии'),
        ),
    ]
