# Generated by Django 4.2.6 on 2023-11-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskcomment_options_taskcomment_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='task_comments', to='tasks.taskcomment', verbose_name='Комментарии'),
        ),
    ]
