# Generated by Django 4.2.6 on 2023-11-25 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_remove_task_comment_task_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'admin'), ('role', 'manager'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер проекта'),
        ),
    ]
