# Generated by Django 4.2.6 on 2023-11-25 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 25, 12, 38, 13, 237211), null=True, verbose_name='Дата'),
        ),
    ]
