# Generated by Django 4.2.6 on 2023-11-25 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_taskcomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 25, 12, 39, 38, 115042, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата'),
        ),
    ]
