# Generated by Django 4.2.6 on 2023-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_files/', verbose_name='Фотография профиля'),
        ),
    ]
