# Generated by Django 4.2.6 on 2023-11-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userpassport', verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='user',
            name='snils',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='СНИЛС'),
        ),
    ]
