# Generated by Django 4.2.6 on 2023-11-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_userpassport_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassport',
            name='owner',
        ),
    ]
