# Generated by Django 4.2.6 on 2023-11-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала события')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет текста')),
                ('bg_color', models.CharField(default='#fff', max_length=7, verbose_name='Цвет фона')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календари',
            },
        ),
    ]
