# Generated by Django 4.2.6 on 2023-11-14 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='project',
        ),
        migrations.AddField(
            model_name='event',
            name='bg_color',
            field=models.CharField(default='#fff', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
