# Generated by Django 4.2.6 on 2023-11-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BotFAQ',
        ),
    ]
