# Generated by Django 4.2.6 on 2023-11-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_user_botfaq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botfaq',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы-ответы'},
        ),
    ]
